name: e_commerce_app
description: E-commerece App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_snack_bar: ^0.3.1
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  dialogs: ^0.0.7
  dio: ^5.3.2
  dropdown_button2: ^2.3.9
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.2
  flutter_observer: ^2.0.0
  flutter_ringtone_player: ^3.2.0
  flutter_screenutil: ^5.8.4
  flutter_stripe: ^9.3.0
  flutter_svg: ^2.0.7
  geolocator: ^10.0.0
  get: ^4.6.5
  get_it: ^7.6.0
  google_maps_flutter: ^2.4.0
  http: any
  image_picker: ^1.0.2
  intl: ^0.18.1
  jiffy: ^6.2.1
  lottie: ^2.4.0
  path: ^1.8.3
  rating_dialog: ^2.0.4
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.12

dev_dependencies:
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
  android_gravity: fill
  
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
